version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  detailed:
    format: "[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/training.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

root:
  level: INFO
  handlers: [console, file]

loggers:
  kedro:
    level: INFO
    handlers: [console, file]
    propagate: false

  gnn_explainer:
    level: INFO
    handlers: [console, file]
    propagate: false

  # Ensure our training module logs are visible
  gnn_explainer.pipelines.training.nodes:
    level: INFO
    handlers: [console, file]
    propagate: false
