# Local environment parameter overrides
#
# Data paths are now configured via environment variable DATA_DIR in conf/base/parameters.yml
# Set in your slurm job file:
#   export DATA_DIR="/projects/aixb/jchung/everycure/influence_estimate/robokop/gnn_clean_baseline/data"
#
# For local development (default): DATA_DIR is not set, uses "data" relative to project root

# Override device setting for server (use CUDA for GPU training)
device: "cuda"
